stages: 
  - build

image: golang:1.16

build-linux:
  stage: build
  script: make ci linux
  artifacts:
    paths:
      - bin/*
build-windows:
  stage: build
  script: make ci windows
  artifacts:
    paths:
      - bin/*